[platformio]
default_envs = deltacrafter-monitor
boards_dir = ${sysenv.TDISPLAY_S3_DIR}/boards
include_dir = include
src_dir = src

[env:deltacrafter-monitor]
platform = espressif32@6.5.0
board = lilygo-t-display-s3
framework = arduino
monitor_speed = 115200
upload_speed = 921600
extra_scripts = post:package.py
; Guard project code against large frames before they consume a task's stack.
build_src_flags = -Werror=frame-larger-than=3072
build_flags =
    -fstack-usage
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DDISABLE_ALL_LIBRARY_WARNINGS
    -DU8G2_USE_LARGE_FONTS
lib_extra_dirs = ${sysenv.TDISPLAY_S3_DIR}/lib
lib_deps =
    bblanchon/ArduinoJson@6.21.5
    olikraus/U8g2@2.35.30
    https://github.com/Axeuh/Axeuh_UI.git#e5185d2c767732df039538129c46a4ea39223abe
lib_ignore =
    arduino-nofrendo
    Adafruit MPR121
    DabbleESP32
    PCF8575 library
    PCA95x5
    lvgl
