[platformio]
default_envs = esp32-usb-player

[env:esp32-usb-player]
platform = espressif32@6.5.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
extra_scripts = pre:web_assets.py
upload_speed = 460800
board_build.partitions = default_8MB.csv
build_unflags = -DARDUINO_USB_MODE=1 -std=gnu++11
build_flags =
    -std=gnu++17
    -DUSE_BLOCK_DEVICE_INTERFACE=1
    -DARDUINO_USB_MODE=0
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DSD_FAT_TYPE=3
    -DUSE_UTF8_LONG_NAMES=1
    -DPLAYER_SD_MMC=1
    -DPLAYER_SD_SCK=36
    -DPLAYER_SD_MISO=37
    -DPLAYER_SD_MOSI=35
    -DPLAYER_SD_CS=34
lib_deps =
    bblanchon/ArduinoJson@6.21.5
    greiman/SdFat@2.2.3
